FROM node:18.12

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --production
RUN yarn add nodemon --no-lockfile
# If you are building your code for production
# RUN npm ci --only=production

CMD [ "yarn", "start" ]
